### PR TITLE
LPS-141119 Blueprint Options Widget

### PR DESCRIPTION
**Pull request by thektan**
Hi Petteri, I was hoping you could take a look if the [`SXPBlueprintOptionsPortletSharedSearchContributor`](https://github.com/peerkar/liferay-portal/pull/7/commits/4e652045924dda63a329c0301ec45d4030ec3448) was properly done.

Currently pausing on this to take a look at other bugs, but the frontend code should be good. The only thing left is looking into the `enabled = false` https://github.com/peerkar/liferay-portal/pull/7/commits/efa938f253c58dccd1aedcf4fd90b4cb9f980630 which gets automatically added with `gw formatSource` if I need to add some type of property somewhere to get it enabled when deploying `search-experiences-web`.

### CODE REVIEW

**Comment by lipusz** [comment]
@thektan 

>Currently pausing on this to take a look at other bugs, but the frontend code should be good. The only thing left is looking into the enabled = false efa938f which gets automatically added with gw formatSource if I need to add some type of property somewhere to get it enabled when deploying search-experiences-web.

See this for explanation: https://liferay.atlassian.net/l/c/cKqEza8B
In short: it's good as it is (enabled = false)

@peerkar Will you be able to push this to Master today?

**Comment by thektan** [comment]
Thanks @lipusz! I'll retest and push this to master today.

**Comment by lipusz** [comment]
ci:test:sf

**Comment by lipusz** [comment]
ci:test:relevant

**Comment by lipusz** [comment]
ci:test:search

**Comment by lipusz** [comment]
Looks like CI is not enabled on this repo.

**Comment by lipusz** [comment]
https://github.com/liferay-search/liferay-portal/pull/240

**Pull request closed without merging**
